### ISSUE TITLE
ModuleNotFoundError: Module not found:

### ISSUE THREAD

**Issue by amaioru0** [danielr18/connected-next-router#110]
When I try to build the nextjs project I get this error:

info  - Creating 
build            
Failed to compile
                 
ModuleNotFoundErr
ror: Package path
ed from package C
omebox\homebox-ne
d-next-router (se
ers\chas13\Deskto
ode_modules\conne
.json)           
                 
                 
> Build error occ
Error: > Build fa
errors           
    at C:\Users\c
mebox-next\node_m
ndex.js:397:19   
    at async Span
chas13\Desktop\ho
modules\next\dist
s:60:20)         
    at async Obje
:\Users\chas13\De
xt\node_modules\n
77:25)           
                 
C:\Users\chas13\D
ext> Module not f
h ./actions is no
C:\Users\ch

**Comment by danielr18** [comment]
Can you create a small reproduction?

**Comment by amaioru0** [comment]
I am not sure how to reproduce it but this is the new error I am getting:

ModuleNotFoundError: Module not found: Error: Package path ./actions is not exported from package /root/homebox-next/node_modules/connected-next-router (see exports field in /root/homebox-next/node_modules/connected-next-router/package.json)

Can you help? @danielr18

**Comment by danielr18** [comment]
@amaioru0 Are you trying to import something from `connected-next-router/actions`?

**Comment by amaioru0** [comment]
No, I am not

**Comment by amaioru0** [comment]
Here is my redux file:

`import { createStore, applyMiddleware, combineReducers } from 'redux'
import { createRouterMiddleware, initialRouterState, routerReducer } from 'connected-next-router'
import { format } from 'url'
import { HYDRATE, createWrapper } from 'next-redux-wrapper'
import Router from 'next/router'

import thunkMiddleware from 'redux-thunk'
import reducers from './reducer'

import { createLogger } from 'redux-logger';

const logger = createLogger();

const bindMiddleware = (middleware) => {
  const { composeWithDevTools } = require('redux-devtools-extension')
  return composeWithDevTools(applyMiddleware(...middleware))
}

const reducer = (state, action) => {
  if (action.type === HYDRATE) {
    const nextState = {
      ...state, // use previous state
      ...action.payload, // apply delta from hydration
    }
    if (typeof window !== 'undefined' && state?.router) {
      // preserve router value on client side navigation
      nextState.router = state.router 
    }
    return nextState
  } else {
    return reducers(state, action)
  }
}

export const initStore = (context) => {
  const routerMiddleware = createRouterMiddleware()
  const { asPath, pathname, query } = context.ctx || Router.router || {};
  let initialState
  if (asPath) {
    const url = format({ pathname, query })
    initialState = {
      router: initialRouterState(url, asPath)
    }
  }
  // return createStore(reducer, initialState, bindMiddleware([routerMiddleware, thunkMiddleware, logger]))
  return createStore(reducer, initialState, bindMiddleware([routerMiddleware, thunkMiddleware]))
}

export const wrapper = createWrapper(initStore)`

**Comment by amaioru0** [comment]
@danielr18

**Comment by amaioru0** [comment]
@danielr18 any advice? Is the only error I am getting and is stoping me from launching my project. I would appreciate your help enormously.

**Comment by danielr18** [comment]
@amaioru0 I can't recreate the issue. Can you create a simple repository with the package versions you are using where the issue occurs?

**Comment by amaioru0** [comment]
Here is the package.json file https://github.com/amaioru0/connected-next-router/tree/main @danielr18 . Thank you for looking into it.

**Comment by amaioru0** [comment]
Hi @danielr18 , I resolved the error. I was importing from actions as you mentioned but didn't realize it.

Thanks for your help!
