### ISSUE TITLE
Question about the route stack or the previous route?

### ISSUE THREAD

**Issue by tastafur** [danielr18/connected-next-router#14]
Hello,

My question is if we can know in any way which was the route from which it came or the stack or stack of routes.

Regards

**Comment by danielr18** [comment]
Depends on where you want to do that. If you use `withRouter` HOC of Next.js, then you could compare the prevProps.pathname with current one, or something.

If you want to keep a stack of routes in Redux, you might want to create a reducer that adds the router state for each LOCATION_CHANGE action that is dispatched in a list.

https://github.com/danielr18/connected-next-router/blob/f96cf21896988a43bb68d77fa10a4188b20f7768/src/actions.js#L7

**Comment by danielr18** [comment]
What's your use case?

**Comment by tastafur** [comment]
My case is that I have an authentication HOC that contains the page, the authentication launches a saga of redux and in the saga I want to know which is the previous URL to know where I come from and I see in the saga that is still loading the state the previous route. Is this correct?
With this operation I can do what I need but I ask better if the operation is correct
<img width="1435" alt="captura de pantalla 2019-02-12 a las 17 42 34" src="https://user-images.githubusercontent.com/11853181/52652648-d3156680-2eee-11e9-887b-cae4929e5d47.png">

**Comment by danielr18** [comment]
Can you explain the flow better?

Is it possible you send the previous URL in the action that runs the saga? And what do you want to do with the previous URL, go back or something?

**Comment by tastafur** [comment]
To this saga I am passing by arguments the pathname of getInitialProps and since it has been rendered it is already in products but the state of the router still shows the previous state
