### ISSUE TITLE
Using in reducer

### ISSUE THREAD

**Issue by stephane-r** [danielr18/connected-next-router#18]
Hello Daniel !

Is it possible to use your module from reducer switch ? For example : 

```
const apiMiddleware = store => next => action => {
  next(action);

  switch (action.type) {
    case LOGIN_THROUGH_API:
      console.log('callApi ...');
      // Push to new route
      break;
  }
};
```

Thank you :muscle:

**Comment by danielr18** [comment]
It should be possible, you could dispatch a navigation action in the middleware.

You might find this useful: https://stackoverflow.com/questions/51186205/how-to-dispatch-actions-from-redux-middleware-in-correct-order

**Comment by danielr18** [comment]
Closed due to inactivity.
