### ISSUE TITLE
isValidElementType is not a function

### ISSUE THREAD

**Issue by haf** [danielr18/connected-next-router#26]
<img width="726" alt="Screenshot 2019-07-30 at 21 43 12" src="https://user-images.githubusercontent.com/193115/62159909-133c9a00-b313-11e9-8c55-c5647ff96846.png">

Connected to routing, but probably not in this library, because it may be a nextjs difference of package versions/mixup that causes this. https://github.com/developit/preact-redux/issues/43 Feel free to close.

**Comment by danielr18** [comment]
You are probably right, I only use Next.js router functions in the beforePopState callback.

```
Router.beforePopState(function(state): boolean {
    const { url, as, options } = state
    change('replaceState', url, as, options, 'POP')
    if (unpatchedMethods.bpsCallback) {
      unpatchedMethods.bpsCallback(state)
    }
    return false
  })

  Router.beforePopState = function(cb: BeforePopStateCallback) {
    unpatchedMethods.bpsCallback = cb
  }
```
