### ISSUE TITLE
Integration in Saga

### ISSUE THREAD

**Issue by dbrrt** [danielr18/connected-next-router#41]
Hello,

Is it possible to use this library in Redux Saga, if so how?

Thanks in advance.

**Comment by danielr18** [comment]
@dbrrt Hello, it's possible to use it.

It depends on what you want to do, you can dispatch Router methods from your sagas, or read the location state from the store.

Let me know if I can help you further

**Comment by dbrrt** [comment]
@danielr18 Thanks for the quick reply, I've tried to wrap my main App with `<Provider>` and `<ConnectedRouter>`, but it had no effect when calling actions from the library. I'm using hooks in my functional components can it be an anti-pattern with your library?

**Comment by danielr18** [comment]
Are you using the redux middleware?

Here's v2 example: https://github.com/danielr18/connected-next-router/tree/v2/examples/basic

**Comment by dbrrt** [comment]
Yes, but probably misconfigured. Will try again. Thanks for the link!

**Comment by danielr18** [comment]
Are you dispatching a navigation action on the server side?

**Comment by dbrrt** [comment]
That was the issue, performing the dispatch on the client side only resolved the issue

**Comment by dbrrt** [comment]
Thanks a lot @danielr18, this issue can be closed, I can try to make a PR with an example for Saga once I've got a moment.

**Comment by danielr18** [comment]
@dbrrt That would be great, thanks!
