### ISSUE TITLE
Doesn't support NextJS 9.0.5

### ISSUE THREAD

**Issue by abbakumov** [danielr18/connected-next-router#47]
Hey! I'm trying to apply your library for Next 9.0.5 and i get the error:
```
[ error ] ./node_modules/connected-next-router/es/patchRouter.js
Module not found: Can't resolve 'next/dist/next-server/lib/router/rewrite-url-for-export' in '{projectPath}/node_modules/connected-next-router/es'
```

That's because you're importing `rewriteUrlForNextExport` [over there](https://github.com/danielr18/connected-next-router/blob/master/src/patchRouter.ts#L7), but NextJS 9.0.5 doesn't exports it.

Updating to next@9.4.4 solves the problem.
Maybe you'll add some info about that or more readable error?

**Comment by danielr18** [comment]
Hi @abbakumov, thanks for reporting this. I'll release the fix in v3.0.2.
