### ISSUE TITLE
State updates after the first useEffect(() => {}, []) called.

### ISSUE THREAD

**Issue by DZakh** [danielr18/connected-next-router#55]
It's very troublesome because you can't normally use values from store.router.location to call some clientSide requests immediately because the value there hasn't updated yet after navigation.  
I was able to manage with it using useRouter, but then here's a question why should I use the lib, if I can't even do something like this. 

To fix it we can update the store on the `routeChangeStart` event, I don't see many downsides in it.

**Comment by danielr18** [comment]
Hi @DZakh, I agree with your concern, one of the purposes of the library is to have an easy drop-in replacement for connected-react-router when migrating a codebase to Next.js, but this is a problem I've encountered myself for example in `getInitialProps` where the route in the reducer is still the one you are currently in.

I don't think it would be right to set the location in `routeChangeStart`, imagine that you have a page that displays the current location, and you navigate to another page with a `getInitialProps` that takes 5 seconds to complete, the result I think we would see is the new location being displayed for those 5 seconds even when you haven't transitioned to the next page yet.

About why you should use the library, I have a similar conclusion to the one in [react-redux-router README](https://github.com/reactjs/react-router-redux#readme).

> This library is not necessary for using Redux together with the Next Router. You can use the two together just fine without any additional libraries. It is useful if you care about recording, persisting, and replaying user actions, using time travel. If you don't care about these features, just can use Redux and Next Router directly.

I would like to make this library more useful, so I'm open to discuss ideas to solve this issue, including routeChangeStart

**Comment by DZakh** [comment]
Thanks for your honest answer. I'll remove the lib from my project and consider using the next/router instead. But before this, I'm gonna leave a few PRs with code that made the lib work for me to some point.

**Comment by danielr18** [comment]
@DZakh Thanks for bringing this up. This should be fixed in V4 with the changes in `patchRouter`. There's now a test case that ensures Next Router state and the router state in Redux are equal on page load / navigation.

https://github.com/danielr18/connected-next-router/blob/309f1444e52eff4b044a419a99d2761068608e9b/src/patchRouter.ts#L22
