### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tastafur** [danielr18/connected-next-router#6]
Hello @danielr18 ,

Some example of how to use this that does not work for me from your PUSH

```
push(href, as, { shallow: false })
```
Thank you.

Regards.

P.D: Thank you for implement the prefeching

**Comment by danielr18** [comment]
I'm failing to recreate this issue. Here's what I tried:

- `props.push('/about?fizz=buzz', undefined, { shallow: true })`
- `props.push('/about?fizz=buzz', '/about?fizz=buzz',, { shallow: true })`
- `props.push({ pathname: '/about', query: { fizz: 'buzz' } }, undefined, { shallow: true })`

Where `props.push` is the `push` action creator wrapped by Redux's `dispatch`.

**Comment by danielr18** [comment]
From Next.js documentation:

> Shallow routing works only for same page URL changes. For an example, let's assume we have another page called about, and you run this:
> 
> Router.push('/?counter=10', '/about?counter=10', { shallow: true })
> Since that's a new page, it'll unload the current page, load the new one and call getInitialProps even though we asked to do shallow routing.

**Comment by danielr18** [comment]
Closed due to inactivity.
