### ISSUE TITLE
[Question] How to get URL parts in a Reducer?

### ISSUE THREAD

**Issue by xaphod** [danielr18/connected-next-router#67]
Hi @danielr18 thanks for making this.

I have a problem where i'm in a reducer, and the current path could be like `/static1/static2/dynamic1/dynamic2`, or it could be `/dynamic1/dynamic2`, and I need to extract & use `dynamic1` and `dynamic2`. I want to find a solution that is agnostic to the values of staticN.

I would have used `useRouter()` and examined the `query`, but i'm in a reducer so I can't.
I was hoping that using `connected-next-router` to put the router's state into redux would let me do this, but I cannot see how. Any ideas? (I've gotten to the point where I can see the router's state in redux)

**Comment by danielr18** [comment]
@xaphod if you are in a reducer, you would only have access to the state of that reducer, not the whole store state.

It seems like you would have to extract  `dynamic1` and `dynamic2` before it gets to the reducer, you would put them in the action data.

**Comment by xaphod** [comment]
Thanks for the quick reply.
This project isn't using redux/actions to navigate, so i'm not sure where/when we would do that.

**Comment by danielr18** [comment]
@xaphod It would have to be done where you dispatch the action. Alternatively, you could handle the `LOCATION_CHANGE` action the library uses in that reducer.

**Comment by xaphod** [comment]
OK thank you
