### ISSUE TITLE
next-routes support

### ISSUE THREAD

**Issue by RomanFrom710** [danielr18/connected-next-router#7]
Readme.md says about [next-routes](https://github.com/fridays/next-routes) support, but it doesn't work out of the box and there's no docs about it.

After digging into `connected-next-router` sources I found that you need to
```js
import {Router} from './routes';

const routerMiddleware = createRouterMiddleware({
  Router,
  methods: {
    push: 'pushRoute',
    replace: 'replaceRoute',
    prefetch: 'prefetchRoute',
  },
}),
```
to get it work properly with `next-routes` router. I'm not sure it can handle all kinds of arguments that these methods should handle, but at least it works with url strings.
I think this worth mentioning in the docs. Thanks!

**Comment by danielr18** [comment]
Yes, that's how it's supposed to be used, and I agree, it should be documented. Will do it soon.
