### ISSUE TITLE
react-router migration question

### ISSUE THREAD

**Issue by kylemh** [danielr18/connected-next-router#72]
I've got the following middleware in place: `thunk.withExtraArgument({ history }),`

How do I pass the relevant object into here when using `connected-next-router`?

**Comment by danielr18** [comment]
I think you won't need a `history` object if using Next.js router, so you wouldn't need that extra argument.

**Comment by kylemh** [comment]
There's a single spot in our code base where basically navigate differently if the history stack only has one item vs. many... I'll find a workaround though. I figured this might be the answer and thought the same thing.
