### ISSUE TITLE
Context `store` not defined with basic setup 

### ISSUE THREAD

**Issue by andrewmartin** [danielr18/connected-next-router#8]
Hi, I'm hitting a fairly strange issue. I've tried looking through the source to figure out why this is happening, but I'm hitting this error:

```Warning: Failed context type: The context `store` is marked as required in `WithConnectedRouter`, but its value is `undefined`.
    in WithConnectedRouter (created by Application)
    in Provider (created by Application)
    in Container (created by Application)
    in Application (created by withRedux(Application))
    in withRedux(Application)```

In `pages/_app.js`:

```
<Provider store={store}>
  <ConnectedRouter>
    <Component {...pageProps} />
  </ConnectedRouter>
</Provider>
```

My `store` is defined as:
```

export default function configureStore(initialState = {}, options) {
  const persistedReducer = persistReducer(
    {
      storage: localForage,
      key: 'primary',
      whitelist: ['client'],
    },
    rootReducer
  );
  const reducer = isServer ? rootReducer : persistedReducer;

  if (options.isServer) {
    initialState.router = initialRouterState(options.asPath);
  }

  const routerMiddleware = createRouterMiddleware();

  return createStore(reducer, initialState, composeWithDevTools(applyMiddleware(thunkMiddleware, routerMiddleware)));
}
```

It should be mentioned that the rest of things (redux, connect on page components, etc) all work fine, and it appears that my `routerMiddleware` is also working. Any ideas why this might be happening or anything I'm doing wrong?

**Comment by danielr18** [comment]
Are you using redux 6?

**Comment by andrewmartin** [comment]
Yes sir I am

**Comment by andrewmartin** [comment]
Does this not work with that version of redux?

**Comment by danielr18** [comment]
Not yet, only up to Redux 5. I'm planning to release a version with Redux 6 support next week, but PRs are welcome, we basically just need to use the new context API to access the Redux store.

**Comment by danielr18** [comment]
Yes! v1.0.0 has been released.
