### ISSUE TITLE
Expose a LocationChangeAction type for TypeScript?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [danielr18/connected-next-router#87]
Similar to #86. I'd be happy to send a PR for both/either of these issues.

[TypeScript playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgGQPIGECCAVAkqgOQH10AJTAgcQFEAaFCAYwEMZgIA7dAC2Y4HMAppkZtOcAL5wAZlAgg4AIkacOg0YIAmAWjUAPGNrkBXGIKiKA3AFgAUHaA)

```ts
example.ts:1:27 - error TS2305: Module '"connected-next-router"' has no exported member 'LocationChangeAction'.

1 import { LOCATION_CHANGE, LocationChangeAction } from "connected-next-router";
```

The type is exported from `connected-react-router`: https://github.com/supasate/connected-react-router/blob/c6609e335c1b6bd3a2fce163d4d19beeb6d6a7ea/index.d.ts#L41

**Comment by danielr18** [comment]
Hey @JoshuaKGoldberg, you can submit the PRs. I’ll review them and publish a new version fairly quick

**Comment by danielr18** [comment]
Thanks @JoshuaKGoldberg. Version 4.1.1 is published

**Comment by JoshuaKGoldberg** [comment]
Amazing, thanks so much for the fast review and release!
