### ISSUE TITLE
peer dependency issue with react-redux@8

### ISSUE THREAD

**Issue by borisilic-ap** [danielr18/connected-next-router#94]
Similar issue to https://github.com/danielr18/connected-next-router/issues/89. We are using `react-redux@8.0.2`. It works with `npm install --force` but it would be good to not have to do that. 

```
npm ERR! Could not resolve dependency:
npm ERR! peer react-redux@"^7.1.0" from connected-next-router@4.2.0
npm ERR! node_modules/connected-next-router
npm ERR!   connected-next-router@"^4.2.0" from the root project
```

**Comment by danielr18** [comment]
Closed with https://github.com/danielr18/connected-next-router/pull/99
